CREATE TABLE `proj_facana`.`ads_fin_fact_day_storeloss_pp` (
  `data_type` varchar(1073741824) DEFAULT NULL COMMENT "数据类型",
  `region` varchar(1073741824) DEFAULT NULL COMMENT "小区",
  `province` varchar(1073741824) DEFAULT NULL COMMENT "省份",
  `managing_area` varchar(1073741824) DEFAULT NULL COMMENT "管理区域",
  `managing_city` varchar(1073741824) DEFAULT NULL COMMENT "管理城市",
  `business_city` varchar(1073741824) DEFAULT NULL COMMENT "经营城市",
  `base_date` varchar(1073741824) DEFAULT NULL COMMENT "日期",
  `brand_detail_abbreviation` varchar(1073741824) DEFAULT NULL COMMENT "品牌",
  `store_no` varchar(1073741824) DEFAULT NULL COMMENT "店铺代码",
  `store_name` varchar(1073741824) DEFAULT NULL COMMENT "店铺名称",
  `store_name_new` varchar(1073741824) DEFAULT NULL COMMENT "店铺名称(新",
  `business_attribute` varchar(1073741824) DEFAULT NULL COMMENT "销售类别",
  `prop_cooperation_mode` varchar(1073741824) DEFAULT NULL COMMENT "物业合作方式",
  `prop_cooperation_conds` varchar(1073741824) DEFAULT NULL COMMENT "物业合作条件",
  `shop_category` varchar(1073741824) DEFAULT NULL COMMENT "店铺类型",
  `business_detail` varchar(1073741824) DEFAULT NULL COMMENT "经营细类",
  `bsgroups_name` varchar(1073741824) DEFAULT NULL COMMENT "商业集团",
  `brand_detail_abbreviation1` varchar(1073741824) DEFAULT NULL COMMENT "主营品牌",
  `brand_detail_abbreviation2` varchar(1073741824) DEFAULT NULL COMMENT "品牌2",
  `brand_series` varchar(1073741824) DEFAULT NULL COMMENT "品牌系",
  `shop_image` varchar(1073741824) DEFAULT NULL COMMENT "店铺形象",
  `region_top` varchar(1073741824) DEFAULT NULL COMMENT "大区",
  `merge_orig_store_no` varchar(1073741824) DEFAULT NULL COMMENT "合并原代码",
  `business_unit` varchar(1073741824) DEFAULT NULL COMMENT "事业部",
  `business_circle_name` varchar(1073741824) DEFAULT NULL COMMENT "所属商圈名称",
  `shopping_mall_name` varchar(1073741824) DEFAULT NULL COMMENT "所属商场名称",
  `store_type_new` varchar(1073741824) DEFAULT NULL COMMENT "店铺类别（新）",
  `org_structure_classification` varchar(1073741824) DEFAULT NULL COMMENT "渠道分类",
  `operation_mode` varchar(1073741824) DEFAULT NULL COMMENT "订单来源",
  `prop_cooperation_conds_new` varchar(1073741824) DEFAULT NULL COMMENT "物业合作条件归集",
  `d2_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "返利_终端收入",
  `d2_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "返利_结款额",
  `d2_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "返利_总部含税成本",
  `d2_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "返利_总部无税毛利",
  `d2_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用",
  `d2_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "返利_B管理费用",
  `d2_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "返利_总部无税营业利润",
  `d2_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用_商场综合收费",
  `d2_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用_工资",
  `d2_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用_浮动工资",
  `d2_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用_装修费",
  `d2_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "返利_经营费用_其他费用",
  `d2_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "返利_店铺贡献",
  `d2_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "返利_管理费用_其他费用",
  `d2_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "返利_总部无税毛利净额",
  `d2t_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_终端收入",
  `d2t_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_结款额",
  `d2t_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_总部含税成本",
  `d2t_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_总部无税毛利",
  `d2t_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用",
  `d2t_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_B管理费用",
  `d2t_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_总部无税营业利润",
  `d2t_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用_商场综合收费",
  `d2t_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用_工资",
  `d2t_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用_浮动工资",
  `d2t_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用_装修费",
  `d2t_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_经营费用_其他费用",
  `d2t_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_店铺贡献",
  `d2t_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_管理费用_其他费用",
  `d2t_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_总部无税毛利净额",
  `d4_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_业绩额",
  `d4_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_牌价收入",
  `d4_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_损益收入",
  `d4_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_结款额",
  `d4_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_总部含税成本",
  `d4_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_总部无税毛利",
  `d4_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_附加税金",
  `d4_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用",
  `d4_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_B管理费用",
  `d4_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_服务收支",
  `d4_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_营业外收支",
  `d4_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_总部无税营业利润",
  `d4_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_商场综合收费",
  `d4_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_工资",
  `d4_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_固定工资",
  `d4_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_浮动工资",
  `d4_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_社保公积金",
  `d4_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_装修费",
  `d4_express` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_快递费",
  `d4_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_经营费用_其他费用",
  `d4_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_店铺贡献",
  `d4_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_工资社保费",
  `d4_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_租金物业费",
  `d4_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_仓储物流费",
  `d4_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_差旅费",
  `d4_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_劳保福利费",
  `d4_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_管理费用_其他费用",
  `d4_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_总部无税毛利净额",
  `d5_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_损益收入",
  `d5_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_结款额",
  `d5_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_总部含税成本",
  `d5_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_总部无税毛利",
  `d5_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用",
  `d5_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_B管理费用",
  `d5_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_总部无税营业利润",
  `d5_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用_商场综合收费",
  `d5_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用_工资",
  `d5_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用_浮动工资",
  `d5_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用_装修费",
  `d5_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_经营费用_其他费用",
  `d5_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_店铺贡献",
  `d5_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_管理费用_其他费用",
  `d5_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_总部无税毛利净额",
  `d6_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_业绩额",
  `d6_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_牌价收入",
  `d6_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_损益收入",
  `d6_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_结款额",
  `d6_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_总部含税成本",
  `d6_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_总部无税毛利",
  `d6_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_附加税金",
  `d6_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用",
  `d6_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_B管理费用",
  `d6_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_服务收支",
  `d6_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_营业外收支",
  `d6_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_总部无税营业利润",
  `d6_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_商场综合收费",
  `d6_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_工资",
  `d6_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_固定工资",
  `d6_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_浮动工资",
  `d6_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_社保公积金",
  `d6_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_装修费",
  `d6_express` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_快递费",
  `d6_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_经营费用_其他费用",
  `d6_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_店铺贡献",
  `d6_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_工资社保费",
  `d6_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_租金物业费",
  `d6_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_仓储物流费",
  `d6_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_差旅费",
  `d6_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_劳保福利费",
  `d6_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_管理费用_其他费用",
  `d6_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_总部无税毛利净额",
  `d7_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_业绩额",
  `d7_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_牌价收入",
  `d7_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_损益收入",
  `d7_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_结款额",
  `d7_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_总部含税成本",
  `d7_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_总部无税毛利",
  `d7_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_附加税金",
  `d7_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用",
  `d7_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_B管理费用",
  `d7_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_服务收支",
  `d7_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_营业外收支",
  `d7_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_总部无税营业利润",
  `d7_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_商场综合收费",
  `d7_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_工资",
  `d7_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_固定工资",
  `d7_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_浮动工资",
  `d7_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_社保公积金",
  `d7_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_装修费",
  `d7_express` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_快递费",
  `d7_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_经营费用_其他费用",
  `d7_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_店铺贡献",
  `d7_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_工资社保费",
  `d7_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_租金物业费",
  `d7_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_仓储物流费",
  `d7_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_差旅费",
  `d7_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_劳保福利费",
  `d7_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_管理费用_其他费用",
  `d7_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_总部无税毛利净额",
  `d8_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_损益收入",
  `d8_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_结款额",
  `d8_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_总部含税成本",
  `d8_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_总部无税毛利",
  `d8_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用",
  `d8_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_B管理费用",
  `d8_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_总部无税营业利润",
  `d8_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用_商场综合收费",
  `d8_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用_工资",
  `d8_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用_浮动工资",
  `d8_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用_装修费",
  `d8_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_经营费用_其他费用",
  `d8_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_店铺贡献",
  `d8_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_管理费用_其他费用",
  `d8_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_总部无税毛利净额",
  `d9_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_业绩额",
  `d9_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_牌价收入",
  `d9_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_损益收入",
  `d9_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_结款额",
  `d9_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_总部含税成本",
  `d9_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_总部无税毛利",
  `d9_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_附加税金",
  `d9_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用",
  `d9_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_B管理费用",
  `d9_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_服务收支",
  `d9_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_营业外收支",
  `d9_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_总部无税营业利润",
  `d9_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_商场综合收费",
  `d9_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_工资",
  `d9_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_固定工资",
  `d9_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_浮动工资",
  `d9_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_社保公积金",
  `d9_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_装修费",
  `d9_express` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_快递费",
  `d9_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_经营费用_其他费用",
  `d9_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_店铺贡献",
  `d9_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_工资社保费",
  `d9_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_租金物业费",
  `d9_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_仓储物流费",
  `d9_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_差旅费",
  `d9_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_劳保福利费",
  `d9_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_管理费用_其他费用",
  `d9_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_总部无税毛利净额",
  `d1t_pf_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_业绩额",
  `d1t_pf_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_牌价收入",
  `d1t_pf_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_损益收入",
  `d1t_pf_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_结款额",
  `d1t_pf_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_总部含税成本",
  `d1t_pf_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_总部无税毛利",
  `d1t_pf_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_附加税金",
  `d1t_pf_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用",
  `d1t_pf_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_B管理费用",
  `d1t_pf_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_服务收支",
  `d1t_pf_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_营业外收支",
  `d1t_pf_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_总部无税营业利润",
  `d1t_pf_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_商场综合收费",
  `d1t_pf_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_工资",
  `d1t_pf_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_固定工资",
  `d1t_pf_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_浮动工资",
  `d1t_pf_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_社保公积金",
  `d1t_pf_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_装修费",
  `d1t_pf_express` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_快递费",
  `d1t_pf_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_经营费用_其他费用",
  `d1t_pf_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_店铺贡献",
  `d1t_pf_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_工资社保费",
  `d1t_pf_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_租金物业费",
  `d1t_pf_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_仓储物流费",
  `d1t_pf_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_差旅费",
  `d1t_pf_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_劳保福利费",
  `d1t_pf_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_管理费用_其他费用",
  `d1t_pf_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_总部无税毛利净额",
  `d1t_pf_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_代运营佣金",
  `d1t_pf_ds_commission_platform` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_平台佣金",
  `d1t_pf_ds_platform_fees` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_平台杂费",
  `d1t_pf_ds_payment_compensation` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_支付赔偿",
  `d1t_pf_ds_advertising_market_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_广告市场费",
  `d1t_pf_cs_self_labor` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_客服自建人工",
  `d1t_pf_cs_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_客服其他支出",
  `d1t_pf_cs_outsource_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_客服外包费用",
  `d1t_pf_total_sal_amt_dpp_st` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_考核店铺双算业绩额",
  `d1t_pf_total_sal_amt_dpp_mc` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_考核管理城市双算业绩额",
  `d1t_pf_total_sal_amt_dpp_rg` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_考核小区双算业绩额",
  `d1t_pf_total_sal_amt_dpp_rt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_考核大区双算业绩额",
  `d1_pf_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_业绩额",
  `d1_pf_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_牌价收入",
  `d1_pf_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_损益收入",
  `d1_pf_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_结款额",
  `d1_pf_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_总部含税成本",
  `d1_pf_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_总部无税毛利",
  `d1_pf_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_附加税金",
  `d1_pf_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用",
  `d1_pf_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_B管理费用",
  `d1_pf_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_服务收支",
  `d1_pf_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_营业外收支",
  `d1_pf_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_总部无税营业利润",
  `d1_pf_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_商场综合收费",
  `d1_pf_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_工资",
  `d1_pf_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_固定工资",
  `d1_pf_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_浮动工资",
  `d1_pf_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_社保公积金",
  `d1_pf_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_装修费",
  `d1_pf_express` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_快递费",
  `d1_pf_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_经营费用_其他费用",
  `d1_pf_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_店铺贡献",
  `d1_pf_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_工资社保费",
  `d1_pf_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_租金物业费",
  `d1_pf_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_仓储物流费",
  `d1_pf_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_差旅费",
  `d1_pf_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_劳保福利费",
  `d1_pf_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_管理费用_其他费用",
  `d1_pf_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_总部无税毛利净额",
  `d1_pf_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_代运营佣金",
  `d1_pf_ds_commission_platform` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台佣金",
  `d1_pf_ds_platform_fees` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台杂费",
  `d1_pf_ds_payment_compensation` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_支付赔偿",
  `d1_pf_ds_advertising_market_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_广告市场费",
  `d1_pf_cs_self_labor` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_客服自建人工",
  `d1_pf_cs_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_客服其他支出",
  `d1_pf_cs_outsource_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_客服外包费用",
  `d1_pf_total_sal_amt_dpp_st` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_考核店铺双算业绩额",
  `d1_pf_total_sal_amt_dpp_mc` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_考核管理城市双算业绩额",
  `d1_pf_total_sal_amt_dpp_rg` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_考核小区双算业绩额",
  `d1_pf_total_sal_amt_dpp_rt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_考核大区双算业绩额",
  `d3t_pf_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_业绩额",
  `d3t_pf_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_牌价收入",
  `d3t_pf_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_损益收入",
  `d3t_pf_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_结款额",
  `d3t_pf_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_总部含税成本",
  `d3t_pf_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_总部无税毛利",
  `d3t_pf_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_附加税金",
  `d3t_pf_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用",
  `d3t_pf_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_B管理费用",
  `d3t_pf_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_服务收支",
  `d3t_pf_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_营业外收支",
  `d3t_pf_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_总部无税营业利润",
  `d3t_pf_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_商场综合收费",
  `d3t_pf_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_工资",
  `d3t_pf_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_固定工资",
  `d3t_pf_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_浮动工资",
  `d3t_pf_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_社保公积金",
  `d3t_pf_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_装修费",
  `d3t_pf_express` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_快递费",
  `d3t_pf_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_经营费用_其他费用",
  `d3t_pf_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_店铺贡献",
  `d3t_pf_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_工资社保费",
  `d3t_pf_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_租金物业费",
  `d3t_pf_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_仓储物流费",
  `d3t_pf_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_差旅费",
  `d3t_pf_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_劳保福利费",
  `d3t_pf_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_管理费用_其他费用",
  `d3t_pf_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_总部无税毛利净额",
  `d3t_pf_total_sal_amt_dpp_st` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_考核店铺双算业绩额",
  `d3t_pf_total_sal_amt_dpp_mc` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_考核管理城市双算业绩额",
  `d3t_pf_total_sal_amt_dpp_rg` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_考核小区双算业绩额",
  `d3t_pf_total_sal_amt_dpp_rt` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_考核大区双算业绩额",
  `d3_pf_total_sal_amt_pp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_业绩额",
  `d3_pf_total_prm_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_牌价收入",
  `d3_pf_total_sal_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_损益收入",
  `d3_pf_settlement_amt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_结款额",
  `d3_pf_hq_taxcost` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_总部含税成本",
  `d3_pf_hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_总部无税毛利",
  `d3_pf_additional_taxes` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_附加税金",
  `d3_pf_operating_exp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用",
  `d3_pf_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_B管理费用",
  `d3_pf_server_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_服务收支",
  `d3_pf_nonoperating_in_out` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_营业外收支",
  `d3_pf_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_总部无税营业利润",
  `d3_pf_comprehensive_mall_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_商场综合收费",
  `d3_pf_salary_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_工资",
  `d3_pf_fix_salary` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_固定工资",
  `d3_pf_float_salary` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_浮动工资",
  `d3_pf_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_社保公积金",
  `d3_pf_decorate_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_装修费",
  `d3_pf_express` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_快递费",
  `d3_pf_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_经营费用_其他费用",
  `d3_pf_store_contribution1` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_店铺贡献",
  `d3_pf_b_salary_social_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_工资社保费",
  `d3_pf_b_rental_property` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_租金物业费",
  `d3_pf_b_warehousing_service` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_仓储物流费",
  `d3_pf_b_travel_expense` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_差旅费",
  `d3_pf_b_labor_insurance_benefits` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_劳保福利费",
  `d3_pf_b_all_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_管理费用_其他费用",
  `d3_pf_hq_notax_gross_net_profit` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_总部无税毛利净额",
  `d3_pf_total_sal_amt_dpp_st` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_考核店铺双算业绩额",
  `d3_pf_total_sal_amt_dpp_mc` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_考核管理城市双算业绩额",
  `d3_pf_total_sal_amt_dpp_rg` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_考核小区双算业绩额",
  `d3_pf_total_sal_amt_dpp_rt` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_考核大区双算业绩额",
  `input_time` varchar(1073741824) DEFAULT NULL COMMENT "INPUT_TIME",
  `input_user` varchar(1073741824) DEFAULT NULL COMMENT "INPUT_USER",
  `etl_create_time` varchar(1073741824) DEFAULT NULL COMMENT "ETL创建时间",
  `etl_update_time` varchar(1073741824) DEFAULT NULL COMMENT "ETL更新时间",
  `platform` varchar(1073741824) DEFAULT NULL COMMENT "平台",
  `d1_pf_ds_return_commission` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台返佣",
  `d1_pf_ds_self_admission_loss` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_自认损失",
  `d1_pf_ds_valuable_coupons` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_有价优惠券",
  `d1_pf_ds_small_payment` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_小额打款",
  `d1_pf_ds_platform_penal` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台罚款",
  `d1t_pf_ds_return_commission` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台返佣",
  `d1t_pf_ds_self_admission_loss` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_自认损失",
  `d1t_pf_ds_valuable_coupons` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_有价优惠券",
  `d1t_pf_ds_small_payment` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_小额打款",
  `d1t_pf_ds_platform_penal` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_平台罚款",
  `d4_ds_return_commission` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_平台返佣",
  `d4_ds_self_admission_loss` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_自认损失",
  `d4_ds_valuable_coupons` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_有价优惠券",
  `d4_ds_small_payment` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_小额打款",
  `d4_ds_platform_penal` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_平台罚款",
  `d4_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_代运营佣金",
  `d4_ds_commission_platform` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_平台佣金",
  `d4_ds_platform_fees` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_平台杂费",
  `d4_ds_payment_compensation` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_支付赔偿",
  `d4_ds_advertising_market_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_广告市场费",
  `d4_cs_self_labor` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_客服自建人工",
  `d4_cs_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_客服其他支出",
  `d4_cs_outsource_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_客服外包费用",
  `d7_ds_return_commission` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_平台返佣",
  `d7_ds_self_admission_loss` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_自认损失",
  `d7_ds_valuable_coupons` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_有价优惠券",
  `d7_ds_small_payment` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_小额打款",
  `d7_ds_platform_penal` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_平台罚款",
  `d7_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_代运营佣金",
  `d7_ds_commission_platform` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_平台佣金",
  `d7_ds_platform_fees` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_平台杂费",
  `d7_ds_payment_compensation` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_支付赔偿",
  `d7_ds_advertising_market_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_广告市场费",
  `d7_cs_self_labor` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_客服自建人工",
  `d7_cs_other_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_客服其他支出",
  `d7_cs_outsource_fee` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_客服外包费用",
  `brand_unit` varchar(1073741824) DEFAULT NULL COMMENT "品牌2所属品牌部",
  `distribution_channel1` varchar(1073741824) DEFAULT NULL COMMENT "销售渠道",
  `d3t_pf_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_代运营佣金",
  `d3_pf_ds_commission_operations` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_代运营佣金",
  `platform_bear_amount_sy` decimal(18, 4) DEFAULT NULL COMMENT "平台优惠_损益",
  `platform_bear_amount_pp` decimal(18, 4) DEFAULT NULL COMMENT "平台优惠_业绩",
  `d1_pf_base_pay` decimal(18, 4) DEFAULT NULL,
  `d1_pf_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d1_pf_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d1_pf_commission_over` decimal(18, 4) DEFAULT NULL,
  `d1_pf_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d1_pf_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d1_pf_other_performance` decimal(18, 4) DEFAULT NULL,
  `d1_pf_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d1_pf_other_money` decimal(18, 4) DEFAULT NULL,
  `d1_pf_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d1_pf_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d1_pf_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_base_pay` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_commission_over` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_other_performance` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_other_money` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d2_base_pay` decimal(18, 4) DEFAULT NULL,
  `d2_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d2_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d2_commission_over` decimal(18, 4) DEFAULT NULL,
  `d2_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d2_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d2_other_performance` decimal(18, 4) DEFAULT NULL,
  `d2_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d2_other_money` decimal(18, 4) DEFAULT NULL,
  `d2_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d2_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d2_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d2t_base_pay` decimal(18, 4) DEFAULT NULL,
  `d2t_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d2t_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d2t_commission_over` decimal(18, 4) DEFAULT NULL,
  `d2t_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d2t_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d2t_other_performance` decimal(18, 4) DEFAULT NULL,
  `d2t_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d2t_other_money` decimal(18, 4) DEFAULT NULL,
  `d2t_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d2t_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d2t_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d3_pf_base_pay` decimal(18, 4) DEFAULT NULL,
  `d3_pf_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d3_pf_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d3_pf_commission_over` decimal(18, 4) DEFAULT NULL,
  `d3_pf_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d3_pf_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d3_pf_other_performance` decimal(18, 4) DEFAULT NULL,
  `d3_pf_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d3_pf_other_money` decimal(18, 4) DEFAULT NULL,
  `d3_pf_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d3_pf_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d3_pf_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_base_pay` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_commission_over` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_other_performance` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_other_money` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d4_base_pay` decimal(18, 4) DEFAULT NULL,
  `d4_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d4_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d4_commission_over` decimal(18, 4) DEFAULT NULL,
  `d4_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d4_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d4_other_performance` decimal(18, 4) DEFAULT NULL,
  `d4_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d4_other_money` decimal(18, 4) DEFAULT NULL,
  `d4_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d4_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d4_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d5_base_pay` decimal(18, 4) DEFAULT NULL,
  `d5_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d5_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d5_commission_over` decimal(18, 4) DEFAULT NULL,
  `d5_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d5_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d5_other_performance` decimal(18, 4) DEFAULT NULL,
  `d5_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d5_other_money` decimal(18, 4) DEFAULT NULL,
  `d5_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d5_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d5_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d6_base_pay` decimal(18, 4) DEFAULT NULL,
  `d6_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d6_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d6_commission_over` decimal(18, 4) DEFAULT NULL,
  `d6_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d6_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d6_other_performance` decimal(18, 4) DEFAULT NULL,
  `d6_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d6_other_money` decimal(18, 4) DEFAULT NULL,
  `d6_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d6_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d6_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d7_base_pay` decimal(18, 4) DEFAULT NULL,
  `d7_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d7_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d7_commission_over` decimal(18, 4) DEFAULT NULL,
  `d7_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d7_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d7_other_performance` decimal(18, 4) DEFAULT NULL,
  `d7_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d7_other_money` decimal(18, 4) DEFAULT NULL,
  `d7_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d7_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d7_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d8_base_pay` decimal(18, 4) DEFAULT NULL,
  `d8_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d8_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d8_commission_over` decimal(18, 4) DEFAULT NULL,
  `d8_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d8_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d8_other_performance` decimal(18, 4) DEFAULT NULL,
  `d8_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d8_other_money` decimal(18, 4) DEFAULT NULL,
  `d8_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d8_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d8_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d9_base_pay` decimal(18, 4) DEFAULT NULL,
  `d9_store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `d9_commission_plan` decimal(18, 4) DEFAULT NULL,
  `d9_commission_over` decimal(18, 4) DEFAULT NULL,
  `d9_overtime_pay` decimal(18, 4) DEFAULT NULL,
  `d9_legal_pay` decimal(18, 4) DEFAULT NULL,
  `d9_other_performance` decimal(18, 4) DEFAULT NULL,
  `d9_other_subsidies` decimal(18, 4) DEFAULT NULL,
  `d9_other_money` decimal(18, 4) DEFAULT NULL,
  `d9_delivery_incentive` decimal(18, 4) DEFAULT NULL,
  `d9_distribution_commission` decimal(18, 4) DEFAULT NULL,
  `d9_incentive_salary` decimal(18, 4) DEFAULT NULL,
  `d1_pf_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d1t_pf_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d2_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d2t_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d3_pf_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d3t_pf_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d4_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d5_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d6_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d7_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d8_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d9_salary_balance` decimal(18, 4) DEFAULT NULL,
  `d1_pf_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a商场合同正常扣费",
  `d1_pf_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a商场合同促销扣费",
  `d1_pf_data03` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a商场临时促销扣费",
  `d1_pf_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a营运费",
  `d1_pf_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a商场促销费",
  `d1_pf_a_property` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a物业费",
  `d1_pf_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a水电费",
  `d1_pf_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_a租赁费",
  `d1t_pf_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a商场合同正常扣费",
  `d1t_pf_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a商场合同促销扣费",
  `d1t_pf_data03` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a商场临时促销扣费",
  `d1t_pf_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a营运费",
  `d1t_pf_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a商场促销费",
  `d1t_pf_a_property` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a物业费",
  `d1t_pf_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a水电费",
  `d1t_pf_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_a租赁费",
  `d2_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "返利_a营运费",
  `d2_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "返利_a商场促销费",
  `d2_a_property` decimal(18, 4) DEFAULT NULL COMMENT "返利_a物业费",
  `d2_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "返利_a水电费",
  `d2_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "返利_a租赁费",
  `d2t_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_a营运费",
  `d2t_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_a商场促销费",
  `d2t_a_property` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_a物业费",
  `d2t_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_a水电费",
  `d2t_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "同期_返利_a租赁费",
  `d3_pf_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a商场合同正常扣费",
  `d3_pf_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a商场合同促销扣费",
  `d3_pf_data03` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a商场临时促销扣费",
  `d3_pf_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a营运费",
  `d3_pf_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a商场促销费",
  `d3_pf_a_property` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a物业费",
  `d3_pf_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a水电费",
  `d3_pf_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_a租赁费",
  `d3t_pf_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_",
  `d3t_pf_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_",
  `d3t_pf_data03` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_",
  `d3t_pf_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_a营运费",
  `d3t_pf_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_a商场促销费",
  `d3t_pf_a_property` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_a物业费",
  `d3t_pf_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_a水电费",
  `d3t_pf_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_考核_a租赁费",
  `d4_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a商场合同正常扣费",
  `d4_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a商场合同促销扣费",
  `d4_data03` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a商场临时促销扣费",
  `d4_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a营运费",
  `d4_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a商场促销费",
  `d4_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a物业费",
  `d4_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a水电费",
  `d4_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_a租赁费",
  `d5_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_a营运费",
  `d5_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_a商场促销费",
  `d5_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_a物业费",
  `d5_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_a水电费",
  `d5_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算返利_a租赁费",
  `d6_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a商场合同正常扣费",
  `d6_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a商场合同促销扣费",
  `d6_data03` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a商场临时促销扣费",
  `d6_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a营运费",
  `d6_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a商场促销费",
  `d6_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a物业费",
  `d6_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a水电费",
  `d6_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算考核_a租赁费",
  `d7_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a商场合同正常扣费",
  `d7_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a商场合同促销扣费",
  `d7_data03` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a商场临时促销扣费",
  `d7_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a营运费",
  `d7_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a商场促销费",
  `d7_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a物业费",
  `d7_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a水电费",
  `d7_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_地区_a租赁费",
  `d8_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_a营运费",
  `d8_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_a商场促销费",
  `d8_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_a物业费",
  `d8_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_a水电费",
  `d8_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_返利_a租赁费",
  `d9_mall_sal_dct` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a商场合同正常扣费",
  `d9_mall_pmt_dcts` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a商场合同促销扣费",
  `d9_data03` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a商场临时促销扣费",
  `d9_a_operating_cost` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a营运费",
  `d9_a_mall_promotion` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a商场促销费",
  `d9_a_property` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a物业费",
  `d9_a_water_electricity` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a水电费",
  `d9_a_rental` decimal(18, 4) DEFAULT NULL COMMENT "预算全年_考核_a租赁费",
  `d1t_pf_staff_number` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_店铺人数(加权人数)",
  `d1t_pf_store_area` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_店铺面积（平方米）",
  `d1_pf_staff_number` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_店铺人数(加权人数)",
  `d1_pf_store_area` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_店铺面积（平方米）",
  `d4_staff_number` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_店铺人数(加权人数)",
  `d4_store_area` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_店铺面积（平方米）",
  `d1_pf_mall_fees` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_地区_商场扣费",
  `d3_pf_mall_fees` decimal(18, 4) DEFAULT NULL COMMENT "业绩版_考核_商场扣费",
  `d1t_pf_mall_fees` decimal(18, 4) DEFAULT NULL COMMENT "同期业绩版_地区_商场扣费",
  `d4_mall_fees` decimal(18, 4) DEFAULT NULL COMMENT "预算地区_商场扣费",
  `d7_mall_fees` decimal(18, 4) DEFAULT NULL,
  `brand_detail_cname` varchar(1073741824) DEFAULT NULL COMMENT "货品品牌中文名称",
  `d11_pf_total_sal_amt_pp` double DEFAULT NULL COMMENT "业绩版_利润口径3_业绩额",
  `d11_pf_total_prm_amt` double DEFAULT NULL COMMENT "业绩版_利润口径3_牌价收入",
  `d11_pf_total_sal_amt` double DEFAULT NULL COMMENT "业绩版_利润口径3_终端收入",
  `d11_pf_settlement_amt` double DEFAULT NULL COMMENT "业绩版_利润口径3_结款额",
  `d11_pf_hq_taxcost` double DEFAULT NULL COMMENT "业绩版_利润口径3_总部含税成本",
  `d11_pf_hq_notax_gross_profit` double DEFAULT NULL COMMENT "业绩版_利润口径3_总部无税毛利",
  `d11_pf_additional_taxes` double DEFAULT NULL COMMENT "业绩版_利润口径3_附加税金",
  `d11_pf_operating_exp` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用",
  `d11_pf_bmanaging_exp` double DEFAULT NULL COMMENT "业绩版_利润口径3_B管理费用",
  `d11_pf_server_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_服务收支",
  `d11_pf_nonoperating_in_out` double DEFAULT NULL COMMENT "业绩版_利润口径3_营业外收支",
  `d11_pf_hq_notax_operating_profit` double DEFAULT NULL COMMENT "业绩版_利润口径3_总部无税营业利润",
  `d11_pf_comprehensive_mall_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_商场综合收费",
  `d11_pf_salary_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_工资",
  `d11_pf_fix_salary` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_固定工资",
  `d11_pf_float_salary` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_浮动工资",
  `d11_pf_social_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_社保公积金",
  `d11_pf_decorate_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_装修费",
  `d11_pf_express` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_快递费",
  `d11_pf_all_other_fee` double DEFAULT NULL COMMENT "业绩版_利润口径3_经营费用_其他费用",
  `d11_pf_store_contribution1` double DEFAULT NULL COMMENT "业绩版_利润口径3_店铺贡献",
  `d11_pf_hq_notax_gross_net_profit` double DEFAULT NULL COMMENT "业绩版_利润口径3_结款无税毛利额",
  `d11t_pf_total_sal_amt_pp` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_业绩额",
  `d11t_pf_total_prm_amt` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_牌价收入",
  `d11t_pf_total_sal_amt` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_终端收入",
  `d11t_pf_settlement_amt` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_结款额",
  `d11t_pf_hq_taxcost` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_总部含税成本",
  `d11t_pf_hq_notax_gross_profit` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_总部无税毛利",
  `d11t_pf_additional_taxes` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_附加税金",
  `d11t_pf_operating_exp` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用",
  `d11t_pf_bmanaging_exp` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_B管理费用",
  `d11t_pf_server_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_服务收支",
  `d11t_pf_nonoperating_in_out` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_营业外收支",
  `d11t_pf_hq_notax_operating_profit` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_总部无税营业利润",
  `d11t_pf_comprehensive_mall_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_商场综合收费",
  `d11t_pf_salary_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_工资",
  `d11t_pf_fix_salary` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_固定工资",
  `d11t_pf_float_salary` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_浮动工资",
  `d11t_pf_social_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_社保公积金",
  `d11t_pf_decorate_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_装修费",
  `d11t_pf_express` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_快递费",
  `d11t_pf_all_other_fee` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_经营费用_其他费用",
  `d11t_pf_store_contribution1` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_店铺贡献",
  `d11t_pf_hq_notax_gross_net_profit` double DEFAULT NULL COMMENT "同期_业绩版_利润口径3_结款无税毛利额",
  `d12_total_sal_amt_pp` double DEFAULT NULL COMMENT "返利_利润口径3_业绩额",
  `d12_total_prm_amt` double DEFAULT NULL COMMENT "返利_利润口径3_牌价收入",
  `d12_total_sal_amt` double DEFAULT NULL COMMENT "返利_利润口径3_终端收入",
  `d12_settlement_amt` double DEFAULT NULL COMMENT "返利_利润口径3_结款额",
  `d12_hq_taxcost` double DEFAULT NULL COMMENT "返利_利润口径3_总部含税成本",
  `d12_hq_notax_gross_profit` double DEFAULT NULL COMMENT "返利_利润口径3_总部无税毛利",
  `d12_additional_taxes` double DEFAULT NULL COMMENT "返利_利润口径3_附加税金",
  `d12_operating_exp` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用",
  `d12_bmanaging_exp` double DEFAULT NULL COMMENT "返利_利润口径3_B管理费用",
  `d12_server_fee` double DEFAULT NULL COMMENT "返利_利润口径3_服务收支",
  `d12_nonoperating_in_out` double DEFAULT NULL COMMENT "返利_利润口径3_营业外收支",
  `d12_hq_notax_operating_profit` double DEFAULT NULL COMMENT "返利_利润口径3_总部无税营业利润",
  `d12_comprehensive_mall_fee` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_商场综合收费",
  `d12_salary_fee` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_工资",
  `d12_fix_salary` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_固定工资",
  `d12_float_salary` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_浮动工资",
  `d12_social_fee` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_社保公积金",
  `d12_decorate_fee` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_装修费",
  `d12_express` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_快递费",
  `d12_all_other_fee` double DEFAULT NULL COMMENT "返利_利润口径3_经营费用_其他费用",
  `d12_store_contribution1` double DEFAULT NULL COMMENT "返利_利润口径3_店铺贡献",
  `d12_hq_notax_gross_net_profit` double DEFAULT NULL COMMENT "返利_利润口径3_结款无税毛利额",
  `d12t_total_sal_amt_pp` double DEFAULT NULL COMMENT "同期_返利_利润口径3_业绩额",
  `d12t_total_prm_amt` double DEFAULT NULL COMMENT "同期_返利_利润口径3_牌价收入",
  `d12t_total_sal_amt` double DEFAULT NULL COMMENT "同期_返利_利润口径3_终端收入",
  `d12t_settlement_amt` double DEFAULT NULL COMMENT "同期_返利_利润口径3_结款额",
  `d12t_hq_taxcost` double DEFAULT NULL COMMENT "同期_返利_利润口径3_总部含税成本",
  `d12t_hq_notax_gross_profit` double DEFAULT NULL COMMENT "同期_返利_利润口径3_总部无税毛利",
  `d12t_additional_taxes` double DEFAULT NULL COMMENT "同期_返利_利润口径3_附加税金",
  `d12t_operating_exp` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用",
  `d12t_bmanaging_exp` double DEFAULT NULL COMMENT "同期_返利_利润口径3_B管理费用",
  `d12t_server_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_服务收支",
  `d12t_nonoperating_in_out` double DEFAULT NULL COMMENT "同期_返利_利润口径3_营业外收支",
  `d12t_hq_notax_operating_profit` double DEFAULT NULL COMMENT "同期_返利_利润口径3_总部无税营业利润",
  `d12t_comprehensive_mall_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_商场综合收费",
  `d12t_salary_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_工资",
  `d12t_fix_salary` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_固定工资",
  `d12t_float_salary` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_浮动工资",
  `d12t_social_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_社保公积金",
  `d12t_decorate_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_装修费",
  `d12t_express` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_快递费",
  `d12t_all_other_fee` double DEFAULT NULL COMMENT "同期_返利_利润口径3_经营费用_其他费用",
  `d12t_store_contribution1` double DEFAULT NULL COMMENT "同期_返利_利润口径3_店铺贡献",
  `d12t_hq_notax_gross_net_profit` double DEFAULT NULL COMMENT "同期_返利_利润口径3_结款无税毛利额",
  `brand_no` varchar(1073741824) DEFAULT NULL COMMENT "品牌部编码",
  `p_mon` varchar(1073741824) DEFAULT NULL COMMENT "yyyymm",
  `pt_mon` date DEFAULT NULL COMMENT "yyyy-mm-dd"
) PARTITION BY (pt_mon) COMMENT ("实时业绩版亏损店单店分析表") PROPERTIES (
  "location" = "oss://ts-bigdata-oss-dev-fin.cn-beijing.oss-dls.aliyuncs.com/user/hive/warehouse/proj_facana.db/ads_fin_fact_day_storeloss_pp"
);