CREATE TABLE ads_pub.ads_fact_day_org_time_shift_sal (
  brd_no STRING COMMENT '品牌部编码',
  org_lno STRING COMMENT '机构原编码',
  org_name STRING COMMENT '机构名称',
  period_date STRING COMMENT '日期型日期',
  time_range STRING COMMENT '时段',
  sal_amt_sy DECIMAL(18,4) COMMENT '业绩额',
  offline_sal_amt_sy DECIMAL(18,4) COMMENT '线下业绩',
  offline_sal_qty_sy DECIMAL(18,4) COMMENT '线下业绩量',
  wholesale_sal_amt_sy DECIMAL(18,4) COMMENT '团购业绩额',
  sy_sal_amt_sy DECIMAL(18,4) COMMENT '私域业绩',
  xhs_sal_amt_sy DECIMAL(18,4) COMMENT '小红书业绩',
  xhs_live_sal_amt_sy DECIMAL(18,4) COMMENT '小红书直播业绩',
  live_sal_amt_sy DECIMAL(18,4) COMMENT '直播业绩',
  uw_cust_sal_nos_num DECIMAL(18,4) COMMENT '非团购线下客单数',
  enter_store_qty BIGINT COMMENT '进店人数',
  online_pick_nos_num DECIMAL(18,4) COMMENT '线上订单数（提货维度）',
  online_pick_send_qty DECIMAL(18,4) COMMENT '线上发货量（提货维度）',
  jsls_pick_nos_num DECIMAL(18,4) COMMENT '即时零售线上订单数（提货维度）',
  jsls_pick_send_qty DECIMAL(18,4) COMMENT '即时零售线上发货量（提货维度）',
  core_sal_qty_sy DECIMAL(18,4) COMMENT '核心款业绩量',
  core_wholesale_sal_qty_sy DECIMAL(18,4) COMMENT '核心款团购业绩量',
  schedul_people_qty DECIMAL(18,4) COMMENT '店铺排班人数',
  uw_top_sal_amt_sy DECIMAL(18,4) COMMENT '非团购销售TOP的业绩量',
  uw_top_biz_inv_qty BIGINT COMMENT '非团购销售TOP的库存量',
  online_accpet_sal_qty DECIMAL(18,4) COMMENT '线上订单接单量（接单维度）',
  noxhs_sal_amt_sy DECIMAL(18,4) COMMENT '业绩额（线下业绩额及私域业绩额(不含小红书直播)）',
  big_region_name STRING COMMENT '大区名称',
  uw_cust_flow_sal_nos_num DECIMAL(18,4) COMMENT '非团购CR客流小票数',
  uw_cust_sal_nos_qty DECIMAL(18,4) COMMENT '非团购线下客单业绩量',
  uw_cust_sal_nos_amt DECIMAL(18,4) COMMENT '非团购线下客单业绩额',
  data_flag STRING COMMENT '数据标志',
  etl_create_time STRING COMMENT 'ETL创建时间',
  etl_update_time STRING COMMENT 'ETL更新时间',
  region_name STRING COMMENT '地区名称',
  mc_name STRING COMMENT '管理城市名称',
  brd_abbr STRING COMMENT '品牌部简称',
  real_schedul_people_qty DECIMAL(18,4) COMMENT '实际店铺排班人数',
  biz_city_name STRING COMMENT '经营城市名称',
  nl_holiday STRING COMMENT '法定节假日',
  pt_day DATE COMMENT '分区')
USING parquet
PARTITIONED BY (pt_day)
COMMENT '日店铺时段业绩排班表'
TBLPROPERTIES (
  'last_modified_time' = '1762418236',
  'transient_lastDdlTime' = '1766044484')