CREATE TABLE `proj_facana`.`dwd_f04_dayone_countbase_pp_new` (
  `base_date` varchar(1073741824) DEFAULT NULL,
  `store_no` varchar(1073741824) DEFAULT NULL,
  `brand_detail_abbreviation` varchar(1073741824) DEFAULT NULL,
  `affiliation` varchar(1073741824) DEFAULT NULL,
  `region` varchar(1073741824) DEFAULT NULL,
  `province` varchar(1073741824) DEFAULT NULL,
  `managing_area` varchar(1073741824) DEFAULT NULL,
  `managing_city` varchar(1073741824) DEFAULT NULL,
  `business_city` varchar(1073741824) DEFAULT NULL,
  `part_area` varchar(1073741824) DEFAULT NULL,
  `company` varchar(1073741824) DEFAULT NULL,
  `brand_character` varchar(1073741824) DEFAULT NULL,
  `store_name` varchar(1073741824) DEFAULT NULL,
  `mall_name` varchar(1073741824) DEFAULT NULL,
  `distribution_level` varchar(1073741824) DEFAULT NULL,
  `business_attribute` varchar(1073741824) DEFAULT NULL,
  `budget_flag` varchar(1073741824) DEFAULT NULL,
  `store_type` varchar(1073741824) DEFAULT NULL,
  `store_status` varchar(1073741824) DEFAULT NULL,
  `same_ratio_flag` varchar(1073741824) DEFAULT NULL,
  `store_open_year` varchar(1073741824) DEFAULT NULL,
  `store_qty` decimal(18, 4) DEFAULT NULL,
  `staff_number` decimal(18, 4) DEFAULT NULL,
  `store_area` decimal(18, 4) DEFAULT NULL,
  `shoes_qty` decimal(18, 4) DEFAULT NULL,
  `clothes_qty` decimal(18, 4) DEFAULT NULL,
  `bag_qty` decimal(18, 4) DEFAULT NULL,
  `parts_qty` decimal(18, 4) DEFAULT NULL,
  `total_prm_amt` decimal(18, 4) DEFAULT NULL,
  `shoes_prm_amt` decimal(18, 4) DEFAULT NULL,
  `clothes_prm_amt` decimal(18, 4) DEFAULT NULL,
  `bag_prm_amt` decimal(18, 4) DEFAULT NULL,
  `parts_prm_amt` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt` decimal(18, 4) DEFAULT NULL,
  `shoes_sal_amt` decimal(18, 4) DEFAULT NULL,
  `clothes_sal_amt` decimal(18, 4) DEFAULT NULL,
  `bag_sal_amt` decimal(18, 4) DEFAULT NULL,
  `parts_sal_amt` decimal(18, 4) DEFAULT NULL,
  `sal_dct` decimal(18, 4) DEFAULT NULL,
  `deduction_rate` decimal(18, 6) DEFAULT NULL,
  `mall_ded_fee_total` decimal(18, 4) DEFAULT NULL,
  `mall_sal_dct` decimal(18, 4) DEFAULT NULL,
  `mall_pmt_dcts` decimal(18, 4) DEFAULT NULL,
  `stm_income` decimal(18, 4) DEFAULT NULL,
  `notax_income` decimal(18, 4) DEFAULT NULL,
  `taxcost` decimal(18, 4) DEFAULT NULL,
  `shoes_sal_cost` decimal(18, 4) DEFAULT NULL,
  `clothes_sal_cost` decimal(18, 4) DEFAULT NULL,
  `bag_sal_cost` decimal(18, 4) DEFAULT NULL,
  `parts_sal_cost` decimal(18, 4) DEFAULT NULL,
  `notax_cost` decimal(18, 4) DEFAULT NULL,
  `hq_taxcost` decimal(18, 4) DEFAULT NULL,
  `hq_shoes_sal_cost` decimal(18, 4) DEFAULT NULL,
  `hq_clothes_sal_cost` decimal(18, 4) DEFAULT NULL,
  `hq_bag_sal_cost` decimal(18, 4) DEFAULT NULL,
  `hq_parts_sal_cost` decimal(18, 4) DEFAULT NULL,
  `hq_notax_cost` decimal(18, 4) DEFAULT NULL,
  `tax_gross_profit` decimal(18, 4) DEFAULT NULL,
  `notax_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_tax_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_shoes_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_clothes_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_bag_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_parts_gross_profit` decimal(18, 4) DEFAULT NULL,
  `hq_notax_gross_profit` decimal(18, 4) DEFAULT NULL,
  `additional_taxes` decimal(18, 4) DEFAULT NULL,
  `operating_exp` decimal(18, 4) DEFAULT NULL,
  `total_operating_exp` decimal(18, 4) DEFAULT NULL,
  `nonoperating_income` decimal(18, 4) DEFAULT NULL,
  `nonoperating_expenditure` decimal(18, 4) DEFAULT NULL,
  `notax_operating_profit` decimal(18, 4) DEFAULT NULL,
  `hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL,
  `income_tax` decimal(18, 4) DEFAULT NULL,
  `hq_income_tax` decimal(18, 4) DEFAULT NULL,
  `notax_net_profit` decimal(18, 4) DEFAULT NULL,
  `hq_notax_net_profit` decimal(18, 4) DEFAULT NULL,
  `discount_balance` decimal(18, 4) DEFAULT NULL,
  `other_income_exp` decimal(18, 4) DEFAULT NULL,
  `net_profit` decimal(18, 4) DEFAULT NULL,
  `operating_cost` decimal(18, 4) DEFAULT NULL,
  `mall_charge` decimal(18, 4) DEFAULT NULL,
  `office_supplies` decimal(18, 4) DEFAULT NULL,
  `repair_cost` decimal(18, 4) DEFAULT NULL,
  `communication_fee` decimal(18, 4) DEFAULT NULL,
  `low_value_cons` decimal(18, 4) DEFAULT NULL,
  `salary` decimal(18, 4) DEFAULT NULL,
  `labor_service_fee` decimal(18, 4) DEFAULT NULL,
  `depreciation_charge` decimal(18, 4) DEFAULT NULL,
  `property_fee` decimal(18, 4) DEFAULT NULL,
  `rental_fee` decimal(18, 4) DEFAULT NULL,
  `social_security_fee` decimal(18, 4) DEFAULT NULL,
  `labor_insurance_fee` decimal(18, 4) DEFAULT NULL,
  `display_installation_fee` decimal(18, 4) DEFAULT NULL,
  `promotion_fee` decimal(18, 4) DEFAULT NULL,
  `packing_charge` decimal(18, 4) DEFAULT NULL,
  `trade_union_funds` decimal(18, 4) DEFAULT NULL,
  `other_fee` decimal(18, 4) DEFAULT NULL,
  `bmanaging_exp` decimal(18, 4) DEFAULT NULL,
  `managing_exp` decimal(18, 4) DEFAULT NULL,
  `financial_exp` decimal(18, 4) DEFAULT NULL,
  `nc_mall_name` varchar(1073741824) DEFAULT NULL,
  `business_attribute3` varchar(1073741824) DEFAULT NULL,
  `ds_managing_city` varchar(1073741824) DEFAULT NULL,
  `ds_business_city` varchar(1073741824) DEFAULT NULL,
  `ds_sal_category` varchar(1073741824) DEFAULT NULL,
  `remark` varchar(1073741824) DEFAULT NULL,
  `hq_managing_exp` decimal(18, 4) DEFAULT NULL,
  `rg_managing_exp` decimal(18, 4) DEFAULT NULL,
  `hq_financial_exp` decimal(18, 4) DEFAULT NULL,
  `rg_financial_exp` decimal(18, 4) DEFAULT NULL,
  `hq_hospitality_business_exp` decimal(18, 4) DEFAULT NULL,
  `hq_office_exp` decimal(18, 4) DEFAULT NULL,
  `hq_repair_cost` decimal(18, 4) DEFAULT NULL,
  `hq_communication_fee` decimal(18, 4) DEFAULT NULL,
  `hq_low_value_cons` decimal(18, 4) DEFAULT NULL,
  `hq_salary` decimal(18, 4) DEFAULT NULL,
  `hq_depreciation_charge` decimal(18, 4) DEFAULT NULL,
  `hq_property_fee` decimal(18, 4) DEFAULT NULL,
  `hq_rental_fee` decimal(18, 4) DEFAULT NULL,
  `hq_freight_costs` decimal(18, 4) DEFAULT NULL,
  `hq_travel_exp` decimal(18, 4) DEFAULT NULL,
  `hq_vehicle_usage_fee` decimal(18, 4) DEFAULT NULL,
  `hq_estate_premium` decimal(18, 4) DEFAULT NULL,
  `hq_planning_publ` decimal(18, 4) DEFAULT NULL,
  `hq_welfare_exp` decimal(18, 4) DEFAULT NULL,
  `hq_decoration_cost` decimal(18, 4) DEFAULT NULL,
  `hq_three_service_fee` decimal(18, 4) DEFAULT NULL,
  `hq_cor_culture_publ` decimal(18, 4) DEFAULT NULL,
  `hq_bad_debts_loss` decimal(18, 4) DEFAULT NULL,
  `hq_social_sec_fee` decimal(18, 4) DEFAULT NULL,
  `hq_consulting_agency_fee` decimal(18, 4) DEFAULT NULL,
  `hq_local_taxes` decimal(18, 4) DEFAULT NULL,
  `hq_conference_fee` decimal(18, 4) DEFAULT NULL,
  `hq_water_and_electricity` decimal(18, 4) DEFAULT NULL,
  `hq_trade_union_funds` decimal(18, 4) DEFAULT NULL,
  `hq_intangible_assets_exp` decimal(18, 4) DEFAULT NULL,
  `hq_promotion_fee` decimal(18, 4) DEFAULT NULL,
  `hq_technology_rd_fee` decimal(18, 4) DEFAULT NULL,
  `hq_quality_inspection_fee` decimal(18, 4) DEFAULT NULL,
  `hq_other_fee` decimal(18, 4) DEFAULT NULL,
  `hq_financial_exp2` decimal(18, 4) DEFAULT NULL,
  `rg_hospitality_business_exp` decimal(18, 4) DEFAULT NULL,
  `rg_office_exp` decimal(18, 4) DEFAULT NULL,
  `rg_repair_cost` decimal(18, 4) DEFAULT NULL,
  `rg_communication_fee` decimal(18, 4) DEFAULT NULL,
  `rg_low_value_cons` decimal(18, 4) DEFAULT NULL,
  `rg_salary` decimal(18, 4) DEFAULT NULL,
  `rg_depreciation_charge` decimal(18, 4) DEFAULT NULL,
  `rg_property_fee` decimal(18, 4) DEFAULT NULL,
  `rg_rental_fee` decimal(18, 4) DEFAULT NULL,
  `rg_freight_costs` decimal(18, 4) DEFAULT NULL,
  `rg_travel_exp` decimal(18, 4) DEFAULT NULL,
  `rg_vehicle_usage_fee` decimal(18, 4) DEFAULT NULL,
  `rg_estate_premium` decimal(18, 4) DEFAULT NULL,
  `rg_planning_publ` decimal(18, 4) DEFAULT NULL,
  `rg_welfare_exp` decimal(18, 4) DEFAULT NULL,
  `rg_decoration_cost` decimal(18, 4) DEFAULT NULL,
  `rg_three_service_fee` decimal(18, 4) DEFAULT NULL,
  `rg_cor_culture_publ` decimal(18, 4) DEFAULT NULL,
  `rg_bad_debts_loss` decimal(18, 4) DEFAULT NULL,
  `rg_social_sec_fee` decimal(18, 4) DEFAULT NULL,
  `rg_consulting_agency_fee` decimal(18, 4) DEFAULT NULL,
  `rg_local_taxes` decimal(18, 4) DEFAULT NULL,
  `rg_conference_fee` decimal(18, 4) DEFAULT NULL,
  `rg_water_and_electricity` decimal(18, 4) DEFAULT NULL,
  `rg_trade_union_funds` decimal(18, 4) DEFAULT NULL,
  `rg_intangible_assets_exp` decimal(18, 4) DEFAULT NULL,
  `rg_promotion_fee` decimal(18, 4) DEFAULT NULL,
  `rg_technology_rd_fee` decimal(18, 4) DEFAULT NULL,
  `rg_quality_inspection_fee` decimal(18, 4) DEFAULT NULL,
  `rg_other_fee` decimal(18, 4) DEFAULT NULL,
  `rg_financial_exp2` decimal(18, 4) DEFAULT NULL,
  `connection_item` varchar(1073741824) DEFAULT NULL,
  `hq_nonoperating_income` decimal(18, 4) DEFAULT NULL,
  `hq_nonoperating_expenditure` decimal(18, 4) DEFAULT NULL,
  `rg_nonoperating_income` decimal(18, 4) DEFAULT NULL,
  `rg_nonoperating_expenditure` decimal(18, 4) DEFAULT NULL,
  `income_statement` decimal(18, 4) DEFAULT NULL,
  `brd_com_service_fee` decimal(18, 4) DEFAULT NULL,
  `income_tax_rate` decimal(18, 4) DEFAULT NULL,
  `hq_income_tax_rate` decimal(18, 4) DEFAULT NULL,
  `adjust_item` varchar(1073741824) DEFAULT NULL,
  `store_using_flag` varchar(1073741824) DEFAULT NULL,
  `nc_brand` varchar(1073741824) DEFAULT NULL,
  `nc_brand2` varchar(1073741824) DEFAULT NULL,
  `analysis_property` varchar(1073741824) DEFAULT NULL,
  `allocation_people_num` decimal(18, 4) DEFAULT NULL,
  `people_number` decimal(18, 4) DEFAULT NULL,
  `overtime_pay` decimal(18, 4) DEFAULT NULL,
  `base_pay` decimal(18, 4) DEFAULT NULL,
  `store_manager_subsidies` decimal(18, 4) DEFAULT NULL,
  `commission_money` decimal(18, 4) DEFAULT NULL,
  `other_money` decimal(18, 4) DEFAULT NULL,
  `nc_name` varchar(1073741824) DEFAULT NULL,
  `nc_no` varchar(1073741824) DEFAULT NULL,
  `report_type` varchar(1073741824) DEFAULT NULL,
  `region_no` varchar(1073741824) DEFAULT NULL,
  `distribution_channel1` varchar(1073741824) DEFAULT NULL,
  `distribution_channel2` varchar(1073741824) DEFAULT NULL,
  `internal_level` varchar(1073741824) DEFAULT NULL,
  `prop_cooperation_mode` varchar(1073741824) DEFAULT NULL,
  `prop_cooperation_conds` varchar(1073741824) DEFAULT NULL,
  `salary_balance` decimal(18, 4) DEFAULT NULL,
  `region_name` varchar(1073741824) DEFAULT NULL,
  `input_time` varchar(1073741824) DEFAULT NULL,
  `input_user` varchar(1073741824) DEFAULT NULL,
  `sequence_code` varchar(1073741824) DEFAULT NULL,
  `express_fee` decimal(18, 4) DEFAULT NULL,
  `data01` decimal(18, 4) DEFAULT NULL,
  `data02` decimal(18, 4) DEFAULT NULL,
  `data03` decimal(18, 4) DEFAULT NULL,
  `data04` decimal(18, 4) DEFAULT NULL,
  `data05` decimal(18, 4) DEFAULT NULL,
  `data06` decimal(18, 4) DEFAULT NULL,
  `data07` decimal(18, 4) DEFAULT NULL,
  `data08` decimal(18, 4) DEFAULT NULL,
  `data09` decimal(18, 4) DEFAULT NULL,
  `data10` decimal(18, 4) DEFAULT NULL,
  `hq_ware_service_fee` decimal(18, 4) DEFAULT NULL,
  `rg_ware_service_fee` decimal(18, 4) DEFAULT NULL,
  `check_remark` varchar(1073741824) DEFAULT NULL,
  `adjust_item1` varchar(1073741824) DEFAULT NULL,
  `adjust_item2` varchar(1073741824) DEFAULT NULL,
  `commission_plan` decimal(18, 4) DEFAULT NULL,
  `commission_over` decimal(18, 4) DEFAULT NULL,
  `incentive_salary` decimal(18, 4) DEFAULT NULL,
  `avg_fact_numnottemp` decimal(18, 4) DEFAULT NULL,
  `legal_pay` decimal(18, 4) DEFAULT NULL,
  `other_performance` decimal(18, 4) DEFAULT NULL,
  `other_subsidies` decimal(18, 4) DEFAULT NULL,
  `plan_open_date` varchar(1073741824) DEFAULT NULL,
  `weighted_number` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_pp` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_dpp` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_dpp_st` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_dpp_mc` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_dpp_rg` decimal(18, 4) DEFAULT NULL,
  `total_sal_amt_dpp_rt` decimal(18, 4) DEFAULT NULL,
  `total_ticket_amt` decimal(18, 4) DEFAULT NULL,
  `uoc_ticket` decimal(18, 4) DEFAULT NULL,
  `uoc_ticket_cou_deduction` decimal(18, 4) DEFAULT NULL,
  `uoc_ticket_vou_discount` decimal(18, 4) DEFAULT NULL,
  `bc_ticket` decimal(18, 4) DEFAULT NULL,
  `bc_ticket_cou_deduction` decimal(18, 4) DEFAULT NULL,
  `bc_ticket_vou_discount` decimal(18, 4) DEFAULT NULL,
  `cou_ticket_deduction` decimal(18, 4) DEFAULT NULL,
  `cou_ticket_buy_amt` decimal(18, 4) DEFAULT NULL,
  `vou_ticket_discount` decimal(18, 4) DEFAULT NULL,
  `customer_settle_amt` decimal(18, 4) DEFAULT NULL,
  `actual_income_amt` decimal(18, 4) DEFAULT NULL,
  `virtual_height_amt` decimal(18, 4) DEFAULT NULL,
  `etl_create_time` varchar(1073741824) DEFAULT NULL,
  `etl_update_time` varchar(1073741824) DEFAULT NULL,
  `etl_flag` varchar(1073741824) DEFAULT NULL,
  `shipping_incentive` decimal(18, 4) DEFAULT NULL,
  `distribution_commission` decimal(18, 4) DEFAULT NULL,
  `platform_bear_amount_sy` decimal(18, 4) DEFAULT NULL,
  `platform_bear_amount_pp` decimal(18, 4) DEFAULT NULL,
  `bottom_basis_name` varchar(1073741824) DEFAULT NULL,
  `total_bottom_amount` decimal(18, 4) DEFAULT NULL,
  `total_bottom_discount_amount` decimal(18, 4) DEFAULT NULL,
  `diff_month_amount` decimal(18, 4) DEFAULT NULL,
  `diff_deduct_amount` decimal(18, 4) DEFAULT NULL,
  `bottom_flag_name` varchar(1073741824) DEFAULT NULL,
  `bottom_complete_rate` decimal(18, 4) DEFAULT NULL,
  `points` decimal(18, 4) DEFAULT NULL,
  `without_brd_data05` decimal(18, 4) DEFAULT NULL COMMENT "剔除品牌费用_总部无税利润",
  `without_brd_data09` decimal(18, 4) DEFAULT NULL COMMENT "剔除品牌费用_总部经营利润",
  `without_brd_hq_notax_operating_profit` decimal(18, 4) DEFAULT NULL COMMENT "剔除品牌费用_总部无税营业利润",
  `without_brd_bmanaging_exp` decimal(18, 4) DEFAULT NULL COMMENT "剔除品牌费用_B管理费用"
)
PRIMARY KEYS (base_date, store_no, brand_detail_abbreviation)
COMMENT ("实时-日实时损益表-业绩版")
PROPERTIES ("location" = "oss://ts-bigdata-oss-hdfs.cn-beijing.oss-dls.aliyuncs.com/user/hive/warehouse/proj_facana.db/dwd_f04_dayone_countbase_pp_new",
 "bucket" = "1",
 "owner" = "hive",
 "sink.watermark-time-zone" = "Asia/Shanghai",
 "snapshot.watermark-idle-timeout" = "10m",
 "changelog-producer" = "input",
 "sink.parallelism" = "8");