CREATE TABLE dws_pub.dws_dim_time (
  period_sdate STRING COMMENT '字符串日期(YYYYMMDD)',
  period_date STRING COMMENT '日期型日期',
  period_id STRING COMMENT '数值日期',
  day_name STRING COMMENT '中文日期',
  week INT COMMENT '星期',
  week_name STRING COMMENT '星期名',
  day_in_month INT COMMENT '月内天数',
  day_in_year INT COMMENT '年内天数',
  week_in_month INT COMMENT '月内周数',
  week_in_year INT COMMENT '年内周数',
  ten_day_month STRING COMMENT '旬',
  month INT COMMENT '月份',
  month_name STRING COMMENT '月份名',
  qtr INT COMMENT '季度',
  qtr_name STRING COMMENT '季度名',
  year STRING COMMENT '年份',
  year_name STRING COMMENT '年份名',
  half_year INT COMMENT '半年',
  half_year_name STRING COMMENT '半年名',
  weekend STRING COMMENT '周末',
  l_year STRING COMMENT '上年日期',
  year_half_year INT COMMENT '年半年',
  year_qtr INT COMMENT '年季度',
  year_month STRING COMMENT '年月',
  l_month_l_day STRING COMMENT '上月月末日期',
  year_week INT COMMENT '年周',
  m_lastday STRING COMMENT '月末日期',
  inv_date STRING COMMENT '历史库存日',
  inv_add_flag INT COMMENT '按天库存算法，1为加法库存,-1为减法库存,0为当前日就是库存日',
  sal_season STRING COMMENT '销售季节',
  nl_sdate STRING COMMENT '农历字符日期',
  nl_date STRING COMMENT '农历中文日期',
  nl_holiday STRING COMMENT '农历节假日',
  nh_flag SMALLINT COMMENT '是否法定节假日(0：否，1：是)',
  week_flag INT COMMENT '周标志(自然周)',
  week_year_name STRING COMMENT '年内周显示(YYYYMMDD-YYYYMMDD)',
  week_month_name STRING COMMENT '月内周显示(YYYYMMDD-YYYYMMDD)',
  nature_week_name STRING COMMENT '自然周显示(YYYYMMDD-YYYYMMDD)',
  fin_year STRING COMMENT '财务年',
  fin_qtr SMALLINT COMMENT '财务季度',
  work_flag STRING COMMENT '是否工作日(0：否，1：是)',
  etl_create_time STRING COMMENT 'ETL创建时间',
  etl_update_time STRING COMMENT 'ETL更新时间',
  nh3_flag SMALLINT COMMENT '是否三薪节假日(0：否，1：是)')
USING parquet
COMMENT 'DIM_时间维度表'
TBLPROPERTIES (
  'last_modified_time' = '1741312968',
  'transient_lastDdlTime' = '1741312968')